#!/usr/bin/env python3
"""Generate a machine-readable evidence manifest for course readiness.

The manifest is intentionally lightweight: it verifies local evidence files and
recorded markers, but it does not fetch external pages or run expensive
capstone acceptance flows. Those commands remain explicit evidence inputs that
instructors rerun and archive before a live offering.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
CS224N_URL = "https://web.stanford.edu/class/cs224n/"

REQUIRED_EVIDENCE_FILES = [
    "README.md",
    "verify_course.py",
    "run_assignment_tests.py",
    "scripts/verify_cs224n_snapshot.py",
    "scripts/verify_frontier_sources.py",
    "scripts/build_course_site_release.py",
    "scripts/build_assignment_release.py",
    "scripts/run_private_autograder.py",
    "docs/presemester-readiness-audit.md",
    "docs/cs224n-current-benchmark-snapshot.md",
    "docs/cs224n-benchmark-crosswalk.md",
    "docs/external-source-verification.md",
    "docs/course-operations-log.md",
    "docs/university-course-quality-audit.md",
    "docs/course-outcome-map.md",
    "docs/core-concept-glossary.md",
    "docs/topic-dependency-map.md",
    "docs/comprehensive-review-study-guide.md",
    "docs/assignment-handout-pack.md",
    "docs/programming-assignment-code-quality-rubric.md",
    "docs/capstone-defense-oral-exam-bank.md",
    "docs/assessment-blueprint-coverage-matrix.md",
    "docs/assessment-item-analysis-psychometrics.md",
    "docs/assessment-item-bank-ledger.md",
    "docs/lecture-note-core-pack.md",
    "docs/lecture-note-sample-pack.md",
    "docs/notation-shape-glossary.md",
    "docs/worked-example-pack.md",
    "docs/lecture-slide-sample-pack.md",
    "docs/recitation-worksheet-pack.md",
    "docs/learning-outcome-attainment-report.md",
    "docs/learning-analytics-remediation-plan.md",
    "docs/weekly-teaching-reflection-adjustment-log.md",
    "docs/teaching-observation-course-evaluation.md",
    "docs/external-expert-review-dossier.md",
    "docs/workload-pacing-calibration.md",
    "docs/course-errata-correction-ledger.md",
    "docs/dataset-model-artifact-registry.md",
    "docs/mathematical-derivation-audit.md",
    "docs/paper-recap-calibration-pack.md",
    "docs/reading-discussion-question-bank.md",
    "docs/paper-to-code-traceability-matrix.md",
    "docs/chapter-claim-audit-ledger.md",
    "docs/chapter-source-map.md",
    "docs/frontier-source-audit.md",
    "docs/frontier-source-evidence-cards.md",
    "docs/frontier-seminar-handout.md",
    "docs/model-benchmark-card-guide.md",
    "docs/project-submission-dossier.md",
    "docs/project-report-template.md",
    "docs/project-report-exemplar-pack.md",
    "docs/project-report-rubric.md",
    "docs/safety-societal-impact-casebook.md",
    "docs/grading-drift-audit-ledger.md",
    "docs/grading-anchor-sample-feedback-pack.md",
    "docs/ta-training-certification.md",
    "docs/private-autograder-operations.md",
]

MARKER_CHECKS = {
    "docs/presemester-readiness-audit.md": [
        "状态：release-candidate",
        "CS224N current benchmark",
        "matched_marker_count=38",
        "missing_marker_count=0",
        "COURSE VERIFY: PASS",
        "ASSIGNMENT TESTS: PASS (11 suite(s))",
        "Full Capstone Acceptance Evidence",
        "pass_rate: 5/5 = 100.0%",
        "SLO: PASS",
        "tokens_per_second: 299.2739 >= 100.0000",
        "latency_ms.p95: 306.9216 <= 2000.0000",
        "final_step: 12",
        "Release Safety Evidence",
        "Known Human Sign-Off Boundaries",
        "LMS / Gradescope configuration",
        "Hidden tests",
        "Project report quality",
    ],
    "docs/cs224n-current-benchmark-snapshot.md": [
        "复核日期：2026-06-05",
        "基准来源：https://web.stanford.edu/class/cs224n/",
        "Stanford / Winter 2026",
        "当前 Schedule 主题证据矩阵",
        "Benchmarking and Evaluation",
        "Reasoning 1 / Reasoning 2",
        "Tokenization and Multilinguality",
        "Tinker and LoRA Without Regret",
        "Assignments 48%",
        "Final Project 49%",
        "Participation 3%",
    ],
    "docs/cs224n-benchmark-crosswalk.md": [
        "CS224N Current Benchmark Snapshot",
        "Current schedule topic evidence",
        "Hugging Face tutorial",
        "Benchmarking and Evaluation",
        "Reasoning",
        "Tokenization and Multilinguality",
        "Frontier Seminar Handout",
    ],
    "docs/core-concept-glossary.md": [
        "Core Concept Glossary",
        "复核日期：2026-06-05",
        "Definition Schema",
        "Core Concepts",
        "Cross-Reference Map",
        "Definition Quality Rules",
        "Maintenance Workflow",
        "Release Checklist",
        "CG-TOKEN-BPE",
        "CG-ATTN",
        "CG-GQA",
        "CG-DPO",
        "CG-RAG",
        "CG-SLO",
        "CG-EVAL-METRIC",
        "CG-SOURCE-BOUNDARY",
        "source boundary",
        "student site release",
    ],
    "docs/topic-dependency-map.md": [
        "Topic Dependency and Spiral Review Map",
        "复核日期：2026-06-05",
        "Dependency Layers",
        "Chapter Dependency Graph",
        "Spiral Review Schedule",
        "Dependency Failure Signals",
        "Student Navigation Rules",
        "Staff Review Workflow",
        "Release Checklist",
        "TD-L0-PREREQ",
        "TD-L8-CAPSTONE",
        "TD-CH01",
        "TD-CH11",
        "TD-SR-W1",
        "TD-SR-W10",
        "TD-F-SHAPE",
        "student site release",
    ],
    "docs/mathematical-derivation-audit.md": [
        "Mathematical Derivation Audit",
        "复核日期：2026-06-05",
        "Audited Derivations",
        "Executable Gate Coverage",
        "DER-01",
        "DER-06",
        "DER-14",
        "Assumptions",
        "Shape / units",
        "Executable evidence",
        "Boundary",
        "check_mathematical_derivation_audit()",
    ],
    "docs/lecture-note-sample-pack.md": [
        "Lecture Note Sample Pack",
        "复核日期：2026-06-05",
        "Sample L1: Tokenization and BPE",
        "Sample L3: Scaled Dot-Product Attention",
        "Sample L9: Cross Entropy and AdamW",
        "Sample L18: Serving SLO and Capacity",
        "Learning goals",
        "Code binding",
        "Source boundary",
        "Post-lecture evidence",
    ],
    "docs/lecture-note-core-pack.md": [
        "Lecture Note Core Pack",
        "复核日期：2026-06-05",
        "Coverage Contract",
        "Core L2: Embedding, Analogy, and RoPE",
        "Core L4: Causal Mask and Cross-Entropy Gradient",
        "Core L6: MHA, GQA, MLA, Norm, and Block Boundaries",
        "Core L12: Speculative Decoding, Constraints, and Frontier Source Boundaries",
        "Core L15: Classic NLP, Encoder-Decoder, BERT, and Evaluation",
        "Code binding",
        "Source boundary",
        "Post-lecture evidence",
    ],
    "docs/notation-shape-glossary.md": [
        "Notation and Shape Glossary",
        "复核日期：2026-06-05",
        "Global Symbols",
        "Module Shape Contracts",
        "Mask and Broadcast Rules",
        "Loss, Objective, and Optimizer Symbols",
        "Serving and Evaluation Units",
        "Disambiguation Rules",
        "Assessment Use",
        "Maintenance Workflow",
        "Release Checklist",
        "NS-01",
        "NS-15",
        "MASK-CAUSAL",
        "MASK-LABEL",
        "beta_dpo",
        "TTFT",
        "UAS",
        "student site release",
    ],
    "docs/worked-example-pack.md": [
        "Worked Example Pack",
        "复核日期：2026-06-05",
        "Example Schema",
        "Core Worked Examples",
        "Recitation Use",
        "Assessment Coverage",
        "Maintenance Workflow",
        "Release Checklist",
        "WE-CH01-BPE",
        "WE-CH02-ROPE",
        "WE-CH03-ATTN",
        "WE-CH04-GQA",
        "WE-CH05-NORM",
        "WE-CH06-PARAMS",
        "WE-CH07-ADAMW",
        "WE-CH08-TOPP",
        "WE-CH09-DPO",
        "WE-CH10-KVCACHE",
        "WE-CH11-METRICS",
        "common failure",
        "source boundary",
    ],
    "docs/lecture-slide-sample-pack.md": [
        "Lecture Slide Sample Pack",
        "复核日期：2026-06-05",
        "Slide Sample Rubric",
        "Sample Deck S1",
        "Sample Deck S4",
        "Slide sequence",
        "Visual plan",
        "Speaker note",
        "Accessibility text",
        "Deck Accessibility Checklist",
        "Release Checklist",
    ],
    "docs/recitation-worksheet-pack.md": [
        "Recitation Worksheet Pack",
        "复核日期：2026-06-05",
        "Worksheet Schema",
        "Worksheet W1",
        "Worksheet W6",
        "shape_table",
        "Failure drill",
        "Paper-to-code link",
        "Exit ticket",
        "Staff Feedback Rubric",
        "Release Checklist",
    ],
    "docs/learning-outcome-attainment-report.md": [
        "Learning Outcome Attainment Report",
        "复核日期：2026-06-05",
        "Attainment Evidence Taxonomy",
        "Outcome Attainment Targets",
        "Current Dry-Run Attainment Matrix",
        "Direct Evidence Collection Plan",
        "Indirect Evidence and Triangulation",
        "Attainment Status Codes",
        "Closing the Loop Actions",
        "dry-run evidence does not prove real student attainment",
        "CO1",
        "CO6",
        "design_ready",
        "LOA-AUTO-ASSIGN",
        "LOA-PROJECT-CLINIC",
    ],
    "docs/learning-analytics-remediation-plan.md": [
        "Learning Analytics and Remediation Plan",
        "复核日期：2026-06-05",
        "Data Sources",
        "Trigger Thresholds",
        "Remediation Playbooks",
        "Weekly Review Workflow",
        "Student-Facing Feedback Template",
        "Operations Log Template",
        "Privacy and Fairness Rules",
        "Release Checklist",
        "LA-QUIZ",
        "TR-SHAPE-30",
        "RP-SHAPE",
    ],
    "docs/teaching-observation-course-evaluation.md": [
        "Teaching Observation and Course Evaluation Dossier",
        "复核日期：2026-06-05",
        "Evaluation Sources",
        "Peer Observation Rubric",
        "Midterm Feedback Response Protocol",
        "End-of-Term Course Review",
        "Current Evaluation Ledger",
        "Student-Visible Response Memo Template",
        "Staff Observation Note Template",
        "Release Checklist",
        "CE-PEER-OBS",
        "CE-MID-SURVEY",
        "CE-END-SURVEY",
        "learning_goal_alignment",
        "technical_accuracy",
        "CE-2026-ITEM-W5",
    ],
    "docs/external-expert-review-dossier.md": [
        "External Expert Review Dossier",
        "复核日期：2026-06-05",
        "Review Scope",
        "Reviewer Independence Rules",
        "Review Rubric",
        "Current External Review Ledger",
        "Response and Closure Workflow",
        "Evidence Packet Template",
        "Severity and Required Response",
        "ER-CONTENT",
        "ER-MATH",
        "ER-SOURCES",
        "ER-ASSIGNMENTS",
        "ER-ASSESSMENT",
        "ER-PROJECTS",
        "ER-ACCESSIBILITY",
        "ER-RELEASE",
        "technical_accuracy",
        "source_traceability",
        "ER-2026-MATH-ROPE",
        "ER-S0",
    ],
    "docs/workload-pacing-calibration.md": [
        "Workload and Pacing Calibration",
        "复核日期：2026-06-05",
        "Calibration Assumptions",
        "Weekly Workload Budget",
        "Difficulty Ladder",
        "Assignment Load Guardrails",
        "Overload Signals and Pacing Actions",
        "10-to-12 Week Expansion Map",
        "Student Time-Planning Template",
        "Staff Review Protocol",
        "Release Checklist",
    ],
    "docs/course-errata-correction-ledger.md": [
        "Course Errata and Correction Ledger",
        "复核日期：2026-06-05",
        "Severity Levels",
        "Ledger Schema",
        "Current Errata Ledger",
        "Intake and Triage Workflow",
        "Announcement Template",
        "SLA and Escalation",
        "Cross-Update Rules",
        "Student-Facing Report Form",
        "ERR-2026-06-05-CH02-01",
        "S1 grading-impacting",
        "verifier gate",
    ],
    "docs/dataset-model-artifact-registry.md": [
        "Dataset, Model, and Artifact Provenance Registry",
        "复核日期：2026-06-05",
        "Artifact Type Taxonomy",
        "Registry Schema",
        "Course Artifact Registry",
        "ART-CH07-SAMPLE-CORPUS",
        "ART-PROJECT-STUDENT-DATA",
        "license_gate",
        "pii_gate",
        "contamination_gate",
        "artifact_manifest",
    ],
    "docs/assessment-item-bank-ledger.md": [
        "Assessment Item Bank Ledger",
        "复核日期：2026-06-05",
        "Exposure Levels",
        "Public-Safe Item Bank",
        "QC-W1-BPE-01",
        "QC-W10-SOURCE-01",
        "QC-MAKEUP-EQUIV-01",
        "Rotation Procedure",
        "Equivalence and Makeup Rules",
        "active_assessment",
    ],
    "docs/assessment-blueprint-coverage-matrix.md": [
        "Assessment Blueprint and Coverage Matrix",
        "复核日期：2026-06-05",
        "Blueprint Dimensions",
        "Outcome Coverage Matrix",
        "Assessment Channel Balance",
        "Cognitive Level Ladder",
        "Sampling and Rotation Rules",
        "Evidence and Grading Gates",
        "Gap Audit",
        "CO1",
        "CO2",
        "CO3",
        "CO4",
        "CO5",
        "CO6",
        "remember",
        "understand",
        "apply",
        "analyze",
        "evaluate",
        "create",
        "auto_gate",
        "capstone_gate",
    ],
    "docs/assessment-item-analysis-psychometrics.md": [
        "Assessment Item Analysis and Psychometrics Guide",
        "复核日期：2026-06-05",
        "Item Analysis Scope",
        "Metric Definitions",
        "Decision Thresholds",
        "Analysis Record Schema",
        "Current Dry-Run Analysis Records",
        "Post-Assessment Workflow",
        "Fairness and Privacy Rules",
        "Release Checklist",
        "item_difficulty_p",
        "item_discrimination_d",
        "distractor_efficiency",
        "short_answer_rubric_fit",
        "subgroup_review_flag",
        "IA-DIFF-HARD",
        "IA-RUBRIC-DRIFT",
        "QC-W9-SLO-01",
    ],
    "docs/paper-recap-calibration-pack.md": [
        "Paper Recap Calibration Pack",
        "复核日期：2026-06-05",
        "Recap Rubric",
        "Anchor Samples",
        "PR-A1",
        "PR-B1",
        "PR-C1",
        "PR-NP1",
        "Required Evidence Fields",
        "TA Calibration Procedure",
        "source_record",
        "technical_detail",
        "boundary",
    ],
    "docs/reading-discussion-question-bank.md": [
        "Reading Discussion Question Bank",
        "复核日期：2026-06-05",
        "Question Schema",
        "Core Question Bank",
        "Discussion Formats",
        "Assessment Sampling Rules",
        "Maintenance Workflow",
        "Release Checklist",
        "RDQ-W0-CLAIM",
        "RDQ-W10-AUDIT",
        "RDQ-F-RECAP",
        "RDQ-R5",
        "question_type",
        "expected_evidence",
        "student site release",
    ],
    "docs/comprehensive-review-study-guide.md": [
        "Comprehensive Review Study Guide",
        "复核日期：2026-06-05",
        "Review Outcomes",
        "Two-Pass Review Schedule",
        "Self-Diagnostic Checklist",
        "Error Log Template",
        "Practice Set Sequence",
        "Staff Use",
        "Release Checklist",
        "CR-O1",
        "CR-S6",
        "CR-D-SOURCE",
        "CR-P-PROJECT",
        "CR-STAFF-CALIBRATE",
        "student site release",
    ],
    "docs/paper-to-code-traceability-matrix.md": [
        "Paper-to-Code Traceability Matrix",
        "复核日期：2026-06-05",
        "Traceability Matrix",
        "P2C-01",
        "P2C-14",
        "A-stable",
        "A-volatile",
        "DER-01",
        "DER-14",
        "assignments/ch01_bpe",
        "assignments/ch11_classic_nlp",
        "Instructor Review Protocol",
        "Release Checklist",
    ],
    "docs/project-submission-dossier.md": [
        "Project Submission Dossier",
        "复核日期：2026-06-05",
        "Dossier Stages",
        "Required File Map",
        "Structured Templates",
        "Stage Acceptance Matrix",
        "TA Review Procedure",
        "DSR-PROPOSAL",
        "DSR-MILESTONE",
        "DSR-FINAL",
        "artifact_manifest",
        "claim_audit",
        "leakage_check",
    ],
    "docs/safety-societal-impact-casebook.md": [
        "Safety and Societal Impact Casebook",
        "复核日期：2026-06-05",
        "Case Analysis Schema",
        "Core Cases",
        "Classroom Use",
        "Assessment Rubric",
        "Staff Review Workflow",
        "Release Checklist",
        "SSI-RAG-MED",
        "SSI-HIRING-BIAS",
        "SSI-PROMPT-INJECT",
        "SSI-LLM-JUDGE",
        "privacy",
        "bias",
        "student site release",
    ],
    "docs/model-benchmark-card-guide.md": [
        "Model and Benchmark Card Guide",
        "复核日期：2026-06-05",
        "Card Schema",
        "Model Card Checklist",
        "Benchmark Card Checklist",
        "Course Card Examples",
        "Claim Rewrite Rules",
        "Student Submission Template",
        "Staff Review Workflow",
        "Release Checklist",
        "MBC-MODEL-ID",
        "MBC-BENCH-TASK",
        "MBC-EX-VOLATILE-CONTEXT",
        "MBC-R6",
        "student site release",
    ],
    "docs/capstone-defense-oral-exam-bank.md": [
        "Capstone Defense and Oral Exam Question Bank",
        "复核日期：2026-06-05",
        "Defense Format",
        "Question Schema",
        "Core Defense Questions",
        "Track-Specific Follow-Ups",
        "Scoring Rubric",
        "Sampling Rules",
        "Oral Record Template",
        "Staff Workflow",
        "Release Checklist",
        "DEF-CONTRIB-01",
        "DEF-EXP-05",
        "DEF-SOURCE-01",
        "DEF-SAMPLE-CO4",
        "student site release",
    ],
    "docs/programming-assignment-code-quality-rubric.md": [
        "Programming Assignment Code Quality Rubric",
        "复核日期：2026-06-05",
        "Rubric Dimensions",
        "Assignment-Specific Review Cues",
        "Manual Review Triggers",
        "Student Self-Check",
        "TA Review Workflow",
        "Release Checklist",
        "CQR-API",
        "CQR-SHAPE",
        "CQR-VECTOR",
        "CQR-NUMERIC",
        "CQR-CH11",
        "CQR-TRIG-HARDCODE",
        "student site release",
    ],
    "docs/frontier-source-evidence-cards.md": [
        "Frontier Source Evidence Cards",
        "复核日期：2026-06-05",
        "Evidence Card Schema",
        "Current Evidence Cards",
        "Upgrade and Downgrade Rules",
        "Release Checklist",
        "FSEC-DSA-2026-0605",
        "FSEC-V4-ARCH-2026-0605",
        "FSEC-V4-MTP-MONITOR-2026-0605",
        "FSEC-ENGRAM-MONITOR-2026-0605",
        "monitor-only",
        "not for scoring",
    ],
    "scripts/verify_frontier_sources.py": [
        "frontier_source_evidence_verification",
        "SOURCE_CHECKS",
        "deepseek_v32_exp_api_news",
        "deepseek_v4_pro_model_card",
        "FSEC-V4-MTP-MONITOR-2026-0605",
        "absent_markers",
        "unexpected_absent_marker_hits",
    ],
    "docs/weekly-teaching-reflection-adjustment-log.md": [
        "Weekly Teaching Reflection and Adjustment Log",
        "复核日期：2026-06-05",
        "Reflection Schema",
        "Evidence Sources",
        "Adjustment Action Bank",
        "Current Reflection Records",
        "Next-Lecture Patch Template",
        "Staff Workflow",
        "Release Checklist",
        "WTR-QUICK",
        "WTR-A-RECAP",
        "WTR-2026-L03-MASK",
        "student site release",
        "course-operations-log.md",
    ],
    "docs/grading-drift-audit-ledger.md": [
        "Grading Drift Audit Ledger",
        "复核日期：2026-06-05",
        "Drift Signals",
        "Calibration Session Schema",
        "Current Calibration Sessions",
        "Double-Grading Sampling Plan",
        "Drift Audit Metrics",
        "Pause and Recalibration Triggers",
        "GD-DELTA-08",
        "CAL-2026-CH02-PRE",
        "capstone_log_mismatch_rate",
        "staff-facing",
    ],
    "docs/ta-training-certification.md": [
        "TA Training and Certification Dossier",
        "复核日期：2026-06-05",
        "Certification Scope",
        "Competency Modules",
        "Certification Matrix",
        "Calibration Practicum",
        "Office Hours Simulation Bank",
        "Privacy, Accessibility, and Integrity Scenario Bank",
        "Current Certification Ledger",
        "Recertification and Escalation",
        "TA-GRADING",
        "TA-PRIVACY",
        "CAL-WRITTEN-01",
        "OH-SHAPE-01",
        "PAI-ACCESS-01",
        "student site release",
    ],
    "docs/external-source-verification.md": [
        "scripts/verify_cs224n_snapshot.py",
        "CS224N",
        "json-out",
    ],
    "docs/course-operations-log.md": [
        "Pre-Semester Readiness Audit",
        "CS224N current benchmark snapshot",
        "前沿来源更新记录",
        "课程总门禁",
    ],
    "README.md": [
        "Pre-Semester Readiness Audit",
        ".venv/bin/python verify_course.py",
        ".venv/bin/python verify_course.py --capstone --training",
    ],
    "scripts/verify_cs224n_snapshot.py": [
        "cs224n_current_snapshot_verification",
        "EXPECTED_MARKERS",
        "Stanford / Winter 2026",
        "Benchmarking and Evaluation",
        "Open Questions in NLP 2026",
    ],
}

VERIFICATION_GATES = [
    {
        "name": "syntax_gate",
        "command": ".venv/bin/python -m py_compile verify_course.py scripts/verify_cs224n_snapshot.py scripts/verify_frontier_sources.py scripts/generate_course_evidence_manifest.py",
        "recorded_marker": "Python 编译无错误",
        "scope": "local verifier scripts",
    },
    {
        "name": "cs224n_current_snapshot",
        "command": ".venv/bin/python scripts/verify_cs224n_snapshot.py",
        "recorded_marker": "status=pass; expected_marker_count=38; matched_marker_count=38; missing_marker_count=0",
        "scope": "official CS224N public page markers",
    },
    {
        "name": "frontier_source_evidence",
        "command": ".venv/bin/python scripts/verify_frontier_sources.py --json-out frontier-sources-2026-06-05.json",
        "recorded_marker": "status=pass; check_count=4; passed_check_count=4; monitor-only absent markers not found",
        "scope": "official/primary DeepSeek and arXiv markers used by frontier source evidence cards",
    },
    {
        "name": "course_verify",
        "command": ".venv/bin/python verify_course.py",
        "recorded_marker": "COURSE VERIFY: PASS",
        "scope": "course structure, links, rendering, source governance, release safety, assignment tests",
    },
    {
        "name": "assignment_public_tests",
        "command": ".venv/bin/python run_assignment_tests.py",
        "recorded_marker": "ASSIGNMENT TESTS: PASS (11 suite(s))",
        "scope": "public assignment suites with reference solutions",
    },
    {
        "name": "full_capstone_acceptance",
        "command": ".venv/bin/python verify_course.py --capstone --training",
        "recorded_marker": "inference ACCEPTANCE: PASS; training ACCEPTANCE: PASS; COURSE VERIFY: PASS",
        "scope": "inference and training capstone release gate",
    },
]

HUMAN_SIGNOFF_BOUNDARIES = [
    "LMS / Gradescope configuration",
    "School-specific policy",
    "Real staff roster",
    "Hidden tests",
    "Live lecture quality",
    "Project report quality",
]

RELEASE_SAFETY_INVARIANTS = [
    "instructor-only docs are excluded from student site releases",
    "assignment reference_solution.py files are excluded",
    "released tests default to student_solution",
    "chapter inline reference solutions are stripped",
    "release-local links are validated",
]


def sha256_file(path: Path) -> str:
    hasher = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            hasher.update(chunk)
    return hasher.hexdigest()


def inspect_file(relative_path: str) -> dict[str, Any]:
    path = ROOT / relative_path
    if not path.exists():
        return {
            "path": relative_path,
            "exists": False,
            "size_bytes": None,
            "sha256": None,
        }
    return {
        "path": relative_path,
        "exists": True,
        "size_bytes": path.stat().st_size,
        "sha256": sha256_file(path),
    }


def check_markers(relative_path: str, markers: list[str]) -> dict[str, Any]:
    path = ROOT / relative_path
    if not path.exists():
        return {
            "path": relative_path,
            "expected_marker_count": len(markers),
            "matched_marker_count": 0,
            "missing_markers": markers,
        }
    text = path.read_text(encoding="utf-8")
    missing = [marker for marker in markers if marker not in text]
    return {
        "path": relative_path,
        "expected_marker_count": len(markers),
        "matched_marker_count": len(markers) - len(missing),
        "missing_markers": missing,
    }


def build_manifest() -> dict[str, Any]:
    generated_at = dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()
    file_entries = [inspect_file(path) for path in REQUIRED_EVIDENCE_FILES]
    marker_entries = [check_markers(path, markers) for path, markers in MARKER_CHECKS.items()]
    missing_required_files = [entry["path"] for entry in file_entries if not entry["exists"]]
    missing_required_markers = {
        entry["path"]: entry["missing_markers"]
        for entry in marker_entries
        if entry["missing_markers"]
    }
    status = "pass" if not missing_required_files and not missing_required_markers else "fail"

    return {
        "mode": "course_evidence_manifest",
        "verification_status": status,
        "generated_at_utc": generated_at,
        "course_benchmark": {
            "name": "Stanford CS224N public-page benchmark",
            "url": CS224N_URL,
            "snapshot_review_date": "2026-06-05",
            "verifier": "scripts/verify_cs224n_snapshot.py",
            "expected_marker_count": 38,
            "recorded_status": "pass",
        },
        "verification_gates": VERIFICATION_GATES,
        "release_safety_invariants": RELEASE_SAFETY_INVARIANTS,
        "human_signoff_boundaries": HUMAN_SIGNOFF_BOUNDARIES,
        "required_evidence_files": file_entries,
        "required_marker_checks": marker_entries,
        "missing_required_files": missing_required_files,
        "missing_required_markers": missing_required_markers,
        "next_actions": [
            "Archive this manifest with the pre-semester readiness audit.",
            "Rerun full capstone acceptance after project code changes.",
            "Refresh the CS224N snapshot verifier before each live offering.",
            "Collect private LMS, Gradescope, staff roster, and hidden-test sign-off evidence outside the student release.",
        ],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json-out", help="optional manifest output path")
    parser.add_argument("--check", action="store_true", help="return nonzero if required files or markers are missing")
    args = parser.parse_args()

    manifest = build_manifest()
    text = json.dumps(manifest, ensure_ascii=False, indent=2)
    if args.json_out:
        Path(args.json_out).write_text(text + "\n", encoding="utf-8")
    print(text)
    if args.check and manifest["verification_status"] != "pass":
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
